/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import core.CLPTask;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;

import org.jacop.examples.fd.Conference;
import org.jacop.examples.fd.PerfectSquare;

import java.time.LocalDate;
import java.time.ZoneOffset;
import java.util.Date;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.WindowConstants;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.IntervalCategoryDataset;
import org.jfree.data.gantt.Task;
import org.jfree.data.gantt.TaskSeries;
import org.jfree.data.gantt.TaskSeriesCollection;


/**
 *
 * @author PF
 */
public class MainWindow extends javax.swing.JFrame {

    private MyChart chart;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        
        chart = new MyChart();
        ganttChartsPanel.setLayout(new GridLayout(1, 1)); 
        ganttChartsPanel.add(chart.createGanttChart());
    }   
    
    public void printText(String text)
    {
        textArea.append(text + "\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        startPanel = new javax.swing.JPanel();
        startTestBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        perfectSquareButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        conferenceButton = new javax.swing.JButton();
        productionSchedulingButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        consolePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        ganttChartsPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startTestBtn.setText("Start");
        startTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTestBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Test inferencing");

        jLabel2.setText("Perfect square");

        perfectSquareButton.setText("Start");
        perfectSquareButton.setToolTipText("");
        perfectSquareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfectSquareButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Conference");

        conferenceButton.setText("Start");
        conferenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conferenceButtonActionPerformed(evt);
            }
        });

        productionSchedulingButton.setText("Start");
        productionSchedulingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productionSchedulingButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Production Scheduling");

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(productionSchedulingButton))
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startTestBtn)
                            .addComponent(perfectSquareButton)
                            .addComponent(conferenceButton))))
                .addGap(107, 107, 107))
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startTestBtn)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(perfectSquareButton)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conferenceButton)
                    .addComponent(jLabel3))
                .addGap(39, 39, 39)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productionSchedulingButton)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Start", startPanel);

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        javax.swing.GroupLayout consolePanelLayout = new javax.swing.GroupLayout(consolePanel);
        consolePanel.setLayout(consolePanelLayout);
        consolePanelLayout.setHorizontalGroup(
            consolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(consolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
        );
        consolePanelLayout.setVerticalGroup(
            consolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
            .addGroup(consolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(consolePanelLayout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Console", consolePanel);

        javax.swing.GroupLayout ganttChartsPanelLayout = new javax.swing.GroupLayout(ganttChartsPanel);
        ganttChartsPanel.setLayout(ganttChartsPanelLayout);
        ganttChartsPanelLayout.setHorizontalGroup(
            ganttChartsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        ganttChartsPanelLayout.setVerticalGroup(
            ganttChartsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Gantt ", ganttChartsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
   * Start Production Scheduling
   * @param  evt Caught event after click
   * @see         JaCoPExamples
   */
    private void productionSchedulingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productionSchedulingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productionSchedulingButtonActionPerformed

   /**
   * Start Conference example
   * @param  evt Caught event after click
   * @see         JaCoPExamples
   */
    private void conferenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conferenceButtonActionPerformed
        // TODO add your handling code here:
        Conference conf = new Conference();
        conf.model();
        if (conf.searchAllAtOnce())
            System.out.println("Solution(s) found");
    }//GEN-LAST:event_conferenceButtonActionPerformed
    
   /**
   * Start PerfectSquare example
   * @param  evt Caught event after click
   * @see         JaCoPExamples
   */
    private void perfectSquareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfectSquareButtonActionPerformed
        // TODO add your handling code here:
        PerfectSquare ps = new PerfectSquare();
        ps.model();
        if (ps.search())
            System.out.println("Solution(s) found");
    }//GEN-LAST:event_perfectSquareButtonActionPerformed

   /**
   * Start CLPTask
   * @param  evt Caught event after click
   * @see         JaCoPExamples
   */
    private void startTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTestBtnActionPerformed
        // TODO add your handling code here:
        printText("Rozpoczynam harmonogramowanie:\n");

        CLPTask task = new CLPTask();
        task.model();
        task.search();
        printText(task.returnStoreString());
    }//GEN-LAST:event_startTestBtnActionPerformed

   /**
   * Here the whole program starts
   * @param  args array of input parameters
   */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conferenceButton;
    private javax.swing.JPanel consolePanel;
    private javax.swing.JPanel ganttChartsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton perfectSquareButton;
    private javax.swing.JButton productionSchedulingButton;
    private javax.swing.JPanel startPanel;
    private javax.swing.JButton startTestBtn;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
